# Generated by Django 5.1 on 2024-08-12 14:54

import mezzanine.pages.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_page_in_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='in_menus',
            field=mezzanine.pages.fields.MenusField(blank=True, choices=((1, 'Top navigation bar'), (2, 'Left-hand tree'), (3, 'Footer')), max_length=100, null=True, verbose_name='Show in menus'),
        ),
    ]
