# Generated by Django 5.0.6 on 2024-07-01 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_alter_blogcategory_id_alter_blogpost_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesKitURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CustomBlogPost',
            fields=[
                ('blogpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blogpost')),
                ('saleskit_urls', models.ManyToManyField(blank=True, to='custom_blog.saleskiturl')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpost',),
        ),
    ]
