# Generated by Django 5.1 on 2024-08-12 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_alter_blogcategory_id_alter_blogpost_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBlogPost',
            fields=[
                ('blogpost_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blogpost')),
                ('saleskit_urls', models.TextField(max_length=1000, null=True)),
                ('direction', models.TextField(default='RTL', max_length=3)),
            ],
            options={
                'verbose_name': 'Custom Blog Post',
                'verbose_name_plural': 'Custom Blog Posts',
            },
            bases=('blog.blogpost',),
        ),
    ]
