# Generated by Django 5.0.6 on 2024-07-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleskiturl',
            name='url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
