# Generated by Django 5.0.6 on 2024-07-07 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcategory_id_alter_blogpost_id_and_more'),
        ('custom_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customblogpost',
            name='blogpost_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blogpost'),
        ),
    ]
