# Generated by Django 5.0.6 on 2024-07-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_blog', '0002_alter_saleskiturl_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_line_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='saleskiturl',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
