# Generated by Django 5.0.6 on 2024-07-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_blog', '0002_alter_customblogpost_blogpost_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='customblogpost',
            name='direction',
            field=models.TextField(default='RTL', max_length=3),
        ),
    ]
