# Generated by Django 5.0.6 on 2024-07-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_blog', '0003_mymodel_alter_saleskiturl_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterModelOptions(
            name='customblogpost',
            options={'verbose_name': 'Custom Blog Post', 'verbose_name_plural': 'Custom Blog Posts'},
        ),
        migrations.RemoveField(
            model_name='customblogpost',
            name='saleskit_url',
        ),
        migrations.AddField(
            model_name='customblogpost',
            name='saleskit_urls',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saleskiturl',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
