# Generated by Django 5.0.6 on 2024-07-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_blog', '0004_delete_mymodel_alter_customblogpost_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesKitURL',
        ),
        migrations.AlterField(
            model_name='customblogpost',
            name='saleskit_urls',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
